//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molimentum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Molimentum.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PostComment_Author_Display {
            get {
                return ResourceManager.GetString("PostComment_Author_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ist zu lang..
        /// </summary>
        internal static string PostComment_Author_Length_Error {
            get {
                return ResourceManager.GetString("PostComment_Author_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name darf nicht leer sein..
        /// </summary>
        internal static string PostComment_Author_Required_Error {
            get {
                return ResourceManager.GetString("PostComment_Author_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar.
        /// </summary>
        internal static string PostComment_Body_Display {
            get {
                return ResourceManager.GetString("PostComment_Body_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar darf nicht leer sein..
        /// </summary>
        internal static string PostComment_Body_Required_Error {
            get {
                return ResourceManager.GetString("PostComment_Body_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string PostComment_Email_Display {
            get {
                return ResourceManager.GetString("PostComment_Email_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail hat ein falsches Format..
        /// </summary>
        internal static string PostComment_Email_Format_Error {
            get {
                return ResourceManager.GetString("PostComment_Email_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail ist zu lang..
        /// </summary>
        internal static string PostComment_Email_Length_Error {
            get {
                return ResourceManager.GetString("PostComment_Email_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail darf nicht leer sein..
        /// </summary>
        internal static string PostComment_Email_Required_Error {
            get {
                return ResourceManager.GetString("PostComment_Email_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string PostComment_PublishDate_Display {
            get {
                return ResourceManager.GetString("PostComment_PublishDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string PostComment_Title_Display {
            get {
                return ResourceManager.GetString("PostComment_Title_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel ist zu lang..
        /// </summary>
        internal static string PostComment_Title_Length_Error {
            get {
                return ResourceManager.GetString("PostComment_Title_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel darf nicht leer sein..
        /// </summary>
        internal static string PostComment_Title_Required_Error {
            get {
                return ResourceManager.GetString("PostComment_Title_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string PostComment_Website_Display {
            get {
                return ResourceManager.GetString("PostComment_Website_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website hat ein falsches Format..
        /// </summary>
        internal static string PostComment_Website_Format_Error {
            get {
                return ResourceManager.GetString("PostComment_Website_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website ist zu lang..
        /// </summary>
        internal static string PostComment_Website_Length_Error {
            get {
                return ResourceManager.GetString("PostComment_Website_Length_Error", resourceCulture);
            }
        }
    }
}
